import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {TransformControls} from './vendor/TransformControls.js';
import {newProject,instance,clone,History,validate,generate,boundsFor,nativeLayout,projectFromLayout} from './core.js';
const $=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token,catalog,assets,lookup,p,history,selection=new Set(),assetSelection=null,candidate=null,candidateBase=null,referenceData=null,dirty=false,flight=false;
const cache=new Map(),models=new Map();let rebuildVersion=0,tool='select',dragStart=null;
function toast(msg,error=false){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,5000);log(msg,error);}
function log(msg,error=false){const e=document.createElement('p');e.textContent=msg;if(error)e.className='error';$('activity').prepend(e);while($('activity').children.length>40)$('activity').lastChild.remove();}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-NativeX-Token':token},body:JSON.stringify(body??{})}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
async function action(fn,button){try{if(button)button.disabled=true;await fn();}catch(e){toast(e.message,true);console.error(e);}finally{if(button)button.disabled=false;}}
function on(id,fn){$(id).onclick=()=>action(fn,$(id));}
const viewport=$('viewport'),renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x111a24);viewport.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,1,.05,50000);camera.position.set(34,30,40);
scene.add(new THREE.HemisphereLight(0xd7f6ff,0x434152,2.5));const sun=new THREE.DirectionalLight(0xffecd1,3.5);sun.position.set(20,40,15);scene.add(sun);const fill=new THREE.DirectionalLight(0x84bbb9,1.5);fill.position.set(-20,8,-15);scene.add(fill);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2,0);controls.enableDamping=true;controls.minDistance=.3;controls.maxDistance=10000;
const grid=new THREE.GridHelper(200,200,0x415761,0x23343e);grid.position.y=-.02;scene.add(grid);
const world=new THREE.Group(),preview=new THREE.Group(),regionGroup=new THREE.Group(),selectGroup=new THREE.Group();scene.add(world,preview,regionGroup,selectGroup);
const pivot=new THREE.Group();scene.add(pivot);const transform=new TransformControls(camera,renderer.domElement);transform.setSpace('world');transform.setRotationSnap(Math.PI/12);scene.add(transform.getHelper());
transform.addEventListener('dragging-changed',e=>{controls.enabled=!e.value&&!flight;if(e.value){dragStart=clone(p);pivot.userData.start=pivot.position.clone();}else if(dragStart){for(const o of p.instances)if(selection.has(o.id)){o.yaw=Math.round(o.yaw/15)*15;if(o.origin==='original')o.origin='override';}history.current=dragStart;commit();dragStart=null;}});
transform.addEventListener('objectChange',()=>{if(!dragStart)return;const delta=pivot.position.clone().sub(pivot.userData.start),angle=pivot.rotation.y;for(const o of p.instances){if(!selection.has(o.id)||o.locked)continue;const original=dragStart.instances.find(x=>x.id===o.id);if(tool==='move')o.position=original.position.map((v,i)=>v+delta.getComponent(i));else if(tool==='rotate'){const origin=pivot.userData.start,relative=new THREE.Vector3(...original.position).sub(origin).applyAxisAngle(new THREE.Vector3(0,1,0),angle).add(origin);o.position=relative.toArray();o.yaw=original.yaw+THREE.MathUtils.radToDeg(angle);}const group=models.get(o.id);if(group){group.position.fromArray(o.position);group.rotation.y=o.yaw*Math.PI/180;}}updateBounds();});
new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(viewport);
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let pointerStart;
renderer.domElement.addEventListener('pointerdown',e=>{pointerStart=[e.clientX,e.clientY];});
renderer.domElement.addEventListener('pointerup',e=>{if(flight||transform.dragging||transform.axis||!pointerStart||Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>4||e.button!==0)return;const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(world.children,true)[0];let id=hit?.object.userData.instanceId;if(!e.shiftKey&&!e.metaKey)selection.clear();if(id){if(selection.has(id))selection.delete(id);else selection.add(id);}updateSelection();});
function disposeHelpers(group){while(group.children.length){const c=group.children[0];group.remove(c);c.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}}
function boxLines(b,color,parent){const box=new THREE.Box3(new THREE.Vector3(...b.min),new THREE.Vector3(...b.max)),h=new THREE.Box3Helper(box,color);parent.add(h);return h;}
function updateBounds(){disposeHelpers(selectGroup);for(const id of selection){const o=p.instances.find(o=>o.id===id),a=o&&lookup.get(o.assetId);if(a?.bounds)boxLines(boundsFor(o,a),o.locked?0xd9aa65:0x75eed9,selectGroup);}}
function drawRegions(){disposeHelpers(regionGroup);boxLines(p.region,0x375a68,regionGroup);for(const b of p.protected)boxLines(b,0xd9a269,regionGroup);['min','max'].forEach(k=>['X','Y','Z'].forEach((a,i)=>$(k+a).value=p.region[k][i]));$('protectedList').innerHTML='';p.protected.forEach((r,i)=>{const el=document.createElement('div');el.innerHTML=`<span>Protected area ${i+1}</span><button aria-label="Remove protected area ${i+1}">×</button>`;el.querySelector('button').onclick=()=>{p.protected.splice(i,1);commit();};$('protectedList').append(el);});}
async function geometry(a){if(!cache.has(a.id))cache.set(a.id,fetch('/api/geometry/'+a.id.slice(3)).then(r=>{if(!r.ok)throw Error('Geometry not available');return r.json();}).then(data=>{data.geometries=data.groups.map(g=>{const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(g.positions,3));geo.setIndex(g.indices);geo.computeVertexNormals();geo.computeBoundingBox();return geo;});return data;}));return cache.get(a.id);}
async function makeModel(o,isPreview=false){const a=lookup.get(o.assetId);if(!a||a.status!=='decoded')return null;const data=await geometry(a),group=new THREE.Group();data.geometries.forEach((geo,i)=>{const material=new THREE.MeshStandardMaterial({color:isPreview?0x63dfc4:([0xa8b6b9,0x7faaa5,0xb7b8ac][i%3]),roughness:.82,metalness:.05,side:THREE.DoubleSide,transparent:isPreview,opacity:isPreview?.58:1});const mesh=new THREE.Mesh(geo,material);mesh.userData.instanceId=o.id;group.add(mesh);});group.position.fromArray(o.position);group.rotation.y=o.yaw*Math.PI/180;group.userData.instanceId=o.id;return group;}
function clearModels(group){for(const g of [...group.children]){group.remove(g);g.traverse(o=>o.material?.dispose());}}
async function rebuild(){const version=++rebuildVersion;$('loading').hidden=false;const built=await Promise.all(p.instances.map(async o=>[o.id,await makeModel(o)]));if(version!==rebuildVersion){built.forEach(([,g])=>g?.traverse(o=>o.material?.dispose()));return;}clearModels(world);models.clear();for(const [id,g]of built)if(g){models.set(id,g);world.add(g);}$('loading').hidden=true;drawRegions();updateSelection();const v=validate(p,assets);$('sceneStats').textContent=`${p.instances.length} objects · ${v.triangles.toLocaleString()} triangles · metres`;$('projectName').value=p.name;$('saveState').textContent=dirty?'Unsaved changes':p.revision?`Saved revision ${p.revision}`:'New project';}
function commit(){dirty=true;history.commit(p);try{localStorage.setItem('nativex.autosave',JSON.stringify(p));}catch{}rebuild();}
function loadProject(next){if(next?.format==='nativex-layout')next=projectFromLayout(next,assets);const check=validate(next,assets);if(check.errors.length)throw Error(check.errors.join('\n'));p=clone(next);history=new History(p);dirty=false;selection.clear();discardCandidate();rebuild().then(()=>focusAll());}
function setTool(next){tool=next;['select','move','rotate'].forEach(n=>$(n+'Tool').classList.toggle('active',n===tool));updateGizmo();}
function updateGizmo(){transform.detach();pivot.rotation.set(0,0,0);const selected=p.instances.filter(o=>selection.has(o.id));if(tool==='select'||flight||!selected.length||selected.some(o=>o.locked))return;const center=selected.reduce((v,o)=>v.add(new THREE.Vector3(...o.position)),new THREE.Vector3()).multiplyScalar(1/selected.length);pivot.position.copy(center);transform.setMode(tool==='move'?'translate':'rotate');transform.showX=tool==='move';transform.showZ=tool==='move';transform.showY=true;transform.setTranslationSnap($('snap').checked?+$('snapStep').value:null);transform.attach(pivot);}
function hierarchy(){const q=$('hierarchySearch').value.toLowerCase();$('hierarchyList').innerHTML='';for(const o of p.instances.filter(o=>o.label.toLowerCase().includes(q))){const el=document.createElement('div');el.className='hierarchyrow'+(selection.has(o.id)?' selected':'');el.innerHTML=`<span>◇</span><span>${escape(o.label)}</span><small>${escape(o.origin)}</small><button class="lock" title="Toggle lock">${o.locked?'▣':'▫'}</button>`;el.onclick=e=>{if(!e.shiftKey)selection.clear();selection.add(o.id);updateSelection();};el.querySelector('.lock').onclick=e=>{e.stopPropagation();o.locked=!o.locked;commit();};$('hierarchyList').append(el);}}
function updateSelection(){updateBounds();updateGizmo();hierarchy();const selected=p.instances.filter(o=>selection.has(o.id)),el=$('selectionPanel');if(!selected.length){el.innerHTML='<div class="emptyicon">⌖</div><h3>Select an object</h3><p>Inspect its source geometry, position and native support.</p>';return;}const o=selected[0],a=lookup.get(o.assetId);el.innerHTML=`<span class="eyebrow">${selected.length>1?selected.length+' OBJECTS SELECTED':escape(o.origin.toUpperCase())}</span><h3>${selected.length>1?'Shared selection':escape(o.label)}</h3><label class="check"><input id="objectLock" type="checkbox" ${selected.every(o=>o.locked)?'checked':''}> Lock selection</label><p>${o.locked?'Unlock to edit.':'Native pivot · absolute game coordinates'}</p><div class="rowfields">${['X','Y','Z'].map((axis,i)=>`<label>${axis} m<input id="pos${axis}" type="number" step="0.25" value="${o.position[i].toFixed(3)}" ${selected.length>1||o.locked?'disabled':''}></label>`).join('')}</div><div class="rowfields"><label>Yaw °<input id="yaw" type="number" step="15" value="${o.yaw}" ${selected.length>1||o.locked?'disabled':''}></label><label>Scale<input value="1 · fixed" disabled></label></div><button id="applyTransform" class="wide" ${selected.length>1||o.locked?'disabled':''}>Apply transform</button><dl><dt>Asset reference</dt><dd>${a.id}</dd><dt>Geometry</dt><dd>${a.vertices} vertices · ${a.triangles} triangles<br>${a.dimensions.join(' × ')} m</dd><dt>Xbox adapter</dt><dd>${a.nativeLayout?'Static terrain supported':'Inspection only — dynamic placement not enabled'}</dd><dt>Source</dt><dd>${escape(a.sourcePath)}</dd><dt>Dependencies</dt><dd>${a.dependencies.map(d=>escape(d.kind)+': '+escape(d.status)).join('<br>')}</dd></dl><details><summary class="muted">${a.sections.length} source sections</summary><pre>${escape(a.sections.map(s=>s.type+' '+s.label+' ('+s.size+' B)').join('\n'))}</pre></details>`;$('applyTransform').onclick=()=>{const position=['X','Y','Z'].map(axis=>Number($('pos'+axis).value)),yaw=Number($('yaw').value);if(!position.every(Number.isFinite)||!Number.isFinite(yaw)){toast('Enter finite transform values.',true);return;}o.position=position;o.yaw=Math.round(yaw/15)*15;if(o.origin==='original')o.origin='override';commit();};$('objectLock').onchange=e=>{selected.forEach(o=>o.locked=e.target.checked);commit();};for(const [i,axis]of ['X','Y','Z'].entries())$('pos'+axis).onkeydown=e=>{if(e.key!=='Enter')return;const v=+e.target.value;if(!Number.isFinite(v))return;o.position[i]=v;if(o.origin==='original')o.origin='override';commit();};$('yaw').onkeydown=e=>{if(e.key!=='Enter')return;o.yaw=Math.round(+e.target.value/15)*15;if(o.origin==='original')o.origin='override';commit();};}
function focusObjects(objects){if(!objects.length){camera.position.set(34,30,40);controls.target.set(0,2,0);return;}const box=new THREE.Box3();objects.forEach(o=>{const a=lookup.get(o.assetId);if(!a?.bounds)return;const b=boundsFor(o,a);box.expandByPoint(new THREE.Vector3(...b.min));box.expandByPoint(new THREE.Vector3(...b.max));});if(box.isEmpty())return;const c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length(),dist=Math.max(4,size*1.1);controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(.8,.65,1).normalize().multiplyScalar(dist));grid.position.set(Math.round(c.x),-.02+Math.min(...objects.map(o=>o.position[1])),Math.round(c.z));controls.update();}
function focusAll(){focusObjects(p.instances);}function focusSelected(){focusObjects(p.instances.filter(o=>selection.has(o.id)));}
async function addAsset(a){if(a.status!=='decoded')throw Error(a.reason);const pos=[controls.target.x,0,controls.target.z];pos[1]=p.region.min[1]-a.bounds[0][1];const o=instance(a,pos);p.instances.push(o);selection=new Set([o.id]);commit();toast('Added '+a.label);}
const thumbObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){thumbObserver.unobserve(entry.target);drawThumbnail(entry.target,lookup.get(entry.target.dataset.asset)).catch(()=>{});}}, {root:$('assetList'),rootMargin:'100px'});
async function drawThumbnail(canvas,a){const d=await geometry(a),ctx=canvas.getContext('2d'),w=136,h=122;canvas.width=w;canvas.height=h;const projected=[];const project=(x,y,z)=>[(x-z)*.707,(x+z)*.34-y*.94];for(const g of d.groups)for(let i=0;i<g.positions.length;i+=3)projected.push(project(...g.positions.slice(i,i+3)));const xs=projected.map(v=>v[0]),ys=projected.map(v=>v[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min((w-22)/Math.max(.1,xmax-xmin),(h-22)/Math.max(.1,ymax-ymin));ctx.clearRect(0,0,w,h);for(const [gi,g]of d.groups.entries()){ctx.fillStyle=['#86a7aa','#aac0bc','#788f9c'][gi%3];ctx.strokeStyle='#354e58';ctx.lineWidth=.45;for(let i=0;i<g.indices.length;i+=3){ctx.beginPath();for(let j=0;j<3;j++){const v=project(...g.positions.slice(g.indices[i+j]*3,g.indices[i+j]*3+3)),x=(v[0]-(xmin+xmax)/2)*scale+w/2,y=(v[1]-(ymin+ymax)/2)*scale+h/2;j?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();if(g.indices.length<5000)ctx.stroke();}}}
function library(){const q=$('search').value.toLowerCase(),category=$('category').value,decoded=$('decodedOnly').checked;let filtered=assets.filter(a=>(!category||a.category===category)&&(!decoded||a.status==='decoded')&&(`${a.label} ${a.category} ${a.id}`).toLowerCase().includes(q));const priorities=['s3:2c701703000303c7','s3:2c701703000303c2','s3:0001466d03e38703','s3:2c701703000601e2'];if(!q&&!category)filtered.sort((a,b)=>(priorities.includes(a.id)?priorities.indexOf(a.id):-1)<0?(priorities.includes(b.id)?1:0):priorities.includes(b.id)?priorities.indexOf(a.id)-priorities.indexOf(b.id):-1);$('assetCount').textContent=filtered.length+' assets';$('assetList').innerHTML='';thumbObserver.disconnect();const renderList=list=>{for(const a of list){const el=document.createElement('div');el.className='assetcard'+(a.status!=='decoded'?' unsupported':'')+(a.id===assetSelection?' selected':'');const thumb=document.createElement('canvas');thumb.dataset.asset=a.id;thumb.setAttribute('aria-label',a.status==='decoded'?'Geometry thumbnail of '+a.label:'No decoded preview');el.append(thumb);const desc=document.createElement('div');desc.innerHTML=`<strong>${escape(a.label)}</strong><small>${escape(a.category)}</small><small>${a.status==='decoded'?a.dimensions.map(n=>n.toFixed(1)).join(' × ')+' m':escape(a.reason)}</small><button ${a.status!=='decoded'?'disabled':''}>+ Add to scene</button>`;el.append(desc);el.onclick=()=>{assetSelection=a.id;document.querySelectorAll('.assetcard').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');if(a.nativeLayout)$('generateAsset').value=a.id;};desc.querySelector('button').onclick=e=>{e.stopPropagation();action(()=>addAsset(a));};$('assetList').append(el);if(a.status==='decoded')thumbObserver.observe(thumb);}};renderList(filtered.slice(0,70));if(filtered.length>70){const more=document.createElement('button');more.className='wide';more.textContent=`Show ${filtered.length-70} more assets`;more.onclick=()=>{more.remove();renderList(filtered.slice(70));};$('assetList').append(more);}}
async function showCandidate(plan){discardCandidate();candidate=plan;candidateBase=JSON.stringify([p.instances,p.region,p.protected]);for(const o of plan.placements){const g=await makeModel(o,true);if(g)preview.add(g);}$('candidateActions').hidden=false;$('plan').textContent=JSON.stringify(plan,null,2);toast(`${plan.placements.length} candidate objects previewed; scene unchanged.`);}
function discardCandidate(){candidate=null;clearModels(preview);$('candidateActions').hidden=true;}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function duplicate(){const added=[];for(const o of p.instances.filter(o=>selection.has(o.id))){const n=clone(o);n.id=crypto.randomUUID();n.position[0]+=3;n.origin='added';n.locked=false;n.sourceTransform=null;added.push(n);}p.instances.push(...added);selection=new Set(added.map(o=>o.id));commit();}
function remove(){p.removedOriginals??=[];for(const o of p.instances.filter(o=>selection.has(o.id)&&!o.locked&&o.origin!=='added'))p.removedOriginals.push({...clone(o),removedAt:new Date().toISOString()});const count=p.instances.filter(o=>selection.has(o.id)&&!o.locked).length;p.instances=p.instances.filter(o=>!selection.has(o.id)||o.locked);selection.clear();commit();toast(`Removed ${count} unlocked instances from the project.`);}
function undo(){const next=history.undo();if(next){p=next;dirty=true;selection.clear();discardCandidate();rebuild();}}function redo(){const next=history.redo();if(next){p=next;dirty=true;selection.clear();rebuild();}}
function setFlight(value){flight=value;controls.enabled=!flight;transform.detach();$('flight').classList.toggle('active',flight);$('crosshair').hidden=!flight;if(flight){const request=renderer.domElement.requestPointerLock?.();request?.catch(()=>{setFlight(false);toast('This browser declined mouse capture; orbit controls restored.',true);});toast('Fly: WASD, Q/E vertical, Shift faster. Mouse to look. Esc exits.');}else{if(document.pointerLockElement)document.exitPointerLock();controls.target.copy(camera.position).add(camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(10));updateGizmo();}}
const keys=new Set();document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&flight)setFlight(false);});document.addEventListener('mousemove',e=>{if(flight&&document.pointerLockElement){const rot=new THREE.Euler().setFromQuaternion(camera.quaternion,'YXZ');rot.y-=e.movementX*.002;rot.x=THREE.MathUtils.clamp(rot.x-e.movementY*.002,-1.5,1.5);camera.quaternion.setFromEuler(rot);}});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;keys.add(e.code);if(e.key==='Escape'&&flight){setFlight(false);return;}if(flight)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('save').click();}else if(e.key.toLowerCase()==='f')focusSelected();else if(e.key.toLowerCase()==='q')setTool('select');else if(e.key.toLowerCase()==='w')setTool('move');else if(e.key.toLowerCase()==='e')setTool('rotate');else if(e.key==='Delete'||e.key==='Backspace')remove();});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(flight){const speed=(keys.has('ShiftLeft')?30:8)*dt;camera.translateX(((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0))*speed);camera.translateZ(((keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0))*speed);camera.position.y+=((keys.has('KeyE')?1:0)-(keys.has('KeyQ')?1:0))*speed;}else controls.update();renderer.render(scene,camera);}requestAnimationFrame(frame);
async function boot(){const init=await fetch('/api/bootstrap').then(r=>r.json());token=init.token;catalog=init.catalog;assets=catalog.assets;lookup=new Map(assets.map(a=>[a.id,a]));$('coverage').textContent=`${assets.filter(a=>a.status==='decoded').length} decoded / ${assets.length} indexed`;
for(const c of catalog.categories.slice(1)){const o=document.createElement('option');o.value=o.textContent=c;$('category').append(o);}for(const a of assets.filter(a=>a.nativeLayout)){const o=document.createElement('option');o.value=a.id;o.textContent=a.label;$('generateAsset').append(o);}$('generateAsset').value='s3:2c701703000303c7';
let start;try{start=JSON.parse(localStorage.getItem('nativex.autosave'));}catch{}if(!start){start=newProject();start.name='Ramp study';start.instances=[instance(lookup.get('s3:2c701703000303c7'),[-3,0,7]),instance(lookup.get('s3:2c701703000303c2'),[17,0,7])];}loadProject(start);library();
for(const id of ['search','category','decodedOnly'])$(id).addEventListener('input',library);$('hierarchySearch').oninput=hierarchy;['select','move','rotate'].forEach(t=>on(t+'Tool',()=>setTool(t)));$('snap').onchange=updateGizmo;$('snapStep').onchange=updateGizmo;on('focus',focusSelected);on('duplicate',duplicate);on('remove',remove);on('undo',undo);on('redo',redo);on('flight',()=>setFlight(!flight));
$('projectName').onchange=e=>{p.name=e.target.value.trim()||'Untitled environment';commit();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabcontent').forEach(x=>x.hidden=x.id!==b.dataset.tab);});
on('panels',()=>document.body.classList.toggle('inspector-open'));on('new',()=>{loadProject(newProject());toast('New project. Previous edits remain in saved revisions.');});on('save',async()=>{const submitted=JSON.stringify(p),r=await api('/api/save',p);if(JSON.stringify(p)===submitted){p=r.project;history.current=clone(p);dirty=false;}else if(p.id===r.project.id){p.revision=r.project.revision;dirty=true;}localStorage.setItem('nativex.autosave',JSON.stringify(p));await rebuild();toast('Saved revision '+r.project.revision+' · '+r.path);});
on('open',async()=>{const list=await fetch('/api/projects').then(r=>r.json());$('savedProjects').innerHTML='';for(const item of list){const b=document.createElement('button');b.textContent=item.name;b.onclick=()=>action(async()=>{const data=await fetch('/api/projects/'+item.file).then(r=>r.json());loadProject(data);$('openDialog').close();toast('Opened '+data.name);});$('savedProjects').append(b);}$('openDialog').showModal();});on('closeDialog',()=>$('openDialog').close());on('importFile',()=>$('projectFile').click());$('projectFile').onchange=e=>action(async()=>{const file=e.target.files[0];if(file){loadProject(JSON.parse(await file.text()));$('openDialog').close();}});
on('export',async()=>{const v=validate(p,assets,{native:true});if(v.errors.length)throw Error(v.errors.join('\n'));const r=await api('/api/export',p);download(p.name.replace(/[^\w -]/g,'')+'.nxlayout.json',r.layout);toast('Exported NativeX layout: '+r.path);});on('validate',()=>{const v=validate(p,assets,{native:true});for(const e of v.errors)log(e,true);for(const w of v.warnings)log(w);toast(v.errors.length?`${v.errors.length} export issue(s). See validation.`:'Scene transforms and native asset references are valid.',!!v.errors.length);});
for(const k of ['min','max'])for(const [i,a]of ['X','Y','Z'].entries())$(k+a).onchange=e=>{const n=+e.target.value;if(!Number.isFinite(n))return;p.region[k][i]=n;if(p.region.min.some((v,i)=>v>=p.region.max[i])){toast('Region minimum must be below maximum on each axis.',true);p=clone(history.current);drawRegions();return;}commit();};
on('regionSelection',()=>{const objects=p.instances.filter(o=>selection.has(o.id));if(!objects.length)throw Error('Select objects first');const boxes=objects.map(o=>boundsFor(o,lookup.get(o.assetId)));p.region={min:[0,1,2].map(i=>Math.min(...boxes.map(b=>b.min[i]))-1),max:[0,1,2].map(i=>Math.max(...boxes.map(b=>b.max[i]))+1)};commit();});on('protect',()=>{p.protected.push({...clone(p.region),id:crypto.randomUUID()});commit();});
$('reference').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{referenceData={name:f.name,data:reader.result};$('referencePreview').src=reader.result;$('referencePreview').hidden=false;};reader.readAsDataURL(f);};on('generateButton',()=>showCandidate(generate(p,assets,{assetId:$('generateAsset').value,count:+$('generateCount').value,seed:$('seed').value,preset:$('preset').value,description:$('description').value,referenceName:referenceData?.name})));on('discard',()=>{discardCandidate();$('plan').textContent='Candidate discarded. Current scene preserved.';});on('accept',()=>{if(!candidate)return;if(candidateBase!==JSON.stringify([p.instances,p.region,p.protected]))throw Error('Scene or protected areas changed. Regenerate the candidate before accepting.');const plan=clone(candidate);plan.placements.forEach(o=>o.id=crypto.randomUUID());const next=clone(p);next.instances.push(...plan.placements);const v=validate(next,assets);if(v.errors.length)throw Error(v.errors.join('\n'));p=next;p.generationHistory.push({...plan,reference:referenceData});selection=new Set(plan.placements.map(o=>o.id));discardCandidate();commit();toast('Candidate accepted. Undo returns to the previous scene.');});
on('connect',async()=>{const s=await api('/api/xbox/status');$('xboxStatus').textContent=`${s.ip} · V37 ${s.ready?'ready':'waiting'} · ${s.active} tracked · ${s.residentTerrainAssets?.length??0} terrain assets resident`;$('xboxReport').textContent=JSON.stringify(s,null,2);toast('Xbox V37 connection verified.');});on('capture',async()=>{const r=await api('/api/xbox/capture');const next=newProject();next.name='NativeX session capture';next.source=r.source;next.instances=r.instances;if(r.instances.length){const boxes=r.instances.map(o=>boundsFor(o,lookup.get(o.assetId)));next.region={min:[0,1,2].map(i=>Math.min(...boxes.map(b=>b.min[i]))-5),max:[0,1,2].map(i=>Math.max(...boxes.map(b=>b.max[i]))+5)};}loadProject(next);toast(`Imported ${r.instances.length} supported NativeX placements; ${r.skipped.length} skipped.`);});on('apply',async()=>{const v=validate(p,assets,{native:true});if(v.errors.length)throw Error(v.errors.join('\n'));$('xboxReport').textContent='Applying through the V37 game-thread mailbox…';const r=await api('/api/xbox/apply',p);$('xboxReport').textContent=JSON.stringify(r,null,2);toast(r.unchanged?'This exact layout is already present; no duplicates created.':`Placed ${r.count} objects. Gameplay collision still needs observation.`);});on('cleanup',async()=>{const r=await api('/api/xbox/cleanup',{projectId:p.id});$('xboxReport').textContent=JSON.stringify(r,null,2);toast(`Cleaned up ${r.removed} Studio-owned objects.`);});
log('642 meshes decoded from the collected archive. No original city placement file has been imported.');window.NativeX={getProject:()=>clone(p),getSelection:()=>[...selection],getCatalog:()=>assets,loadProject,geometry,validate:()=>validate(p,assets),select:id=>{selection=new Set([id]);updateSelection();},focusAll};}
boot().catch(e=>{toast('Startup failed: '+e.message,true);console.error(e);});
